name: Build and Deploy
on:
  push:
    branches:
      - master

jobs:
  install-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '12.12.0'
          registry-url: https://registry.npmjs.org/
      - name: Install dependencies
        run: |
          npm install
      - name: install gh-pages
        run: |
          npm install -g gh-pages
      - name: predeploy
        run: |
          npm run build
      - name: predeploy
        run: |
          gh-pages -d build
